### ISSUE TITLE
Program goes blank using Samsung Galaxy S10+ (Example Images Attached)

### ISSUE THREAD

**Issue by atkeeler** [ganeshrvel/openmtp#212] opened 2021-01-04 22:39 UTC
I went ahead and downloaded the latest version of the program today and I'm currently trying to connect it to my MacBook Pro (running MacOS Catalina 10.15.7), and for some reason the program goes blank when I hit the refresh button. I know it's connected properly because I ren Samsung Smart Switch and it was detected. I plugged in my Moto G3 just to try it and It works fine with that. Not sure what's up with it, but I attached screenshots for examples _(censored my name on Smart Switch for privacy reasons)_.

Edit: I've tried making an error report for this occurrence, but each time I try it generates a block error log.

<img width="1677" alt="Screen Shot 2021-01-04 at 5 37 26 PM" src="https://user-images.githubusercontent.com/68133091/103586667-8e649100-4eb3-11eb-994e-ba37e6b824d1.png">
<img width="770" alt="Screen Shot 2021-01-04 at 5 26 15 PM" src="https://user-images.githubusercontent.com/68133091/103586670-90c6eb00-4eb3-11eb-8fe2-06a9c67631bd.png">
<img width="1792" alt="Screen Shot 2021-01-04 at 5 21 35 PM" src="https://user-images.githubusercontent.com/68133091/103586672-915f8180-4eb3-11eb-82f9-451f3d6a83fa.png">

**Comment by ganeshrvel** [comment] 2021-01-06 13:42
I will take a look. Thanks for reporting

**Comment by xNS5** [comment] 2021-01-08 21:40
I'm having a similar issue on my S8+ w/ MacOS 10.15.7

I want to say the program gets stuck while refreshing, so that might be a place to look.

I seem to recall reading somewhere that Smart Switch interferes with MTP, but as I don't have it installed on my devices I can't say that's the cause.

**Comment by ganeshrvel** [comment] 2021-01-11 11:08
@xNS5 @atkeeler 

Could you guys send me the error log by going to Help menu -> Report Bugs -> Email error logs -> Attach the log file to the email.

Cheers

**Comment by xNS5** [comment] 2021-01-12 02:01
I was right that smart switch interferes with MTP!

If you check out [this](https://medium.com/@farazfazli/how-i-reverse-engineered-keis-and-sidesync-and-fixed-mtp-8949acbb1c29) link, I found a few kext files leftover from when I had smart switch (which was a while ago). Once I uninstalled them, I was able to use the program without issue.

**Comment by atkeeler** [comment] 2021-01-27 20:15
@ganeshrvel

After removing SmartSwitch and all the Samsung drivers from my MacBook Pro (as suggested by @xNS5), I am able to access my S10+ through OpenMTP. I would recommend adding into the description that if a user has SmartSwitch installed on their Mac that it might interfere with the program due to the Samsung drivers that are installed on the system.

**Comment by ganeshrvel** [comment] 2021-01-28 06:16
Reopening this issue until its fixed.

**Comment by xNS5** [comment] 2021-01-28 06:21
The issue has been fixed. The solution is to uninstall Smart Switch and remove the com.devguru.* kext files. I don't think there is anything you can do on your end to prevent these drivers from interfering with OpenMTP other than adding a disclaimer to the project README.

**Comment by ganeshrvel** [comment] 2021-01-28 06:24
i will have to make a note inside the faqs sections of the app

**Comment by ganeshrvel** [comment] 2021-02-21 19:04
Updated the FAQ section in the latest version and README file. Closing this issue.

**Closed by ganeshrvel** 2021-02-21 19:04 UTC
