### ISSUE TITLE
Support Garmin devices

### ISSUE THREAD

**Issue by wadewegner** [ganeshrvel/openmtp#153] opened 2020-07-25 18:03 UTC
I have a Forerunner 945. It'd be awesome if openmtp supported these Garmin devices.

**Comment by ganeshrvel** [comment] 2020-10-17 20:27
I'm currently working on a new mtp kernel and hopefully we will have support for a wider range of devices.

**Comment by ganeshrvel** [comment] 2020-12-08 09:39
@wadewegner 

Could you download the latest community beta version of OpenMTP from https://drive.google.com/file/d/1wpSlkGWZKe4-nRYcdJaPVA3Y6kOBMTsO/view?usp=sharing and let me know whether your device is recognized?

Cheers

**Comment by miharekar** [comment] 2020-12-11 13:59
@ganeshrvel the beta does not work with Garmin FR945

**Comment by ganeshrvel** [comment] 2020-12-11 14:01
Could you send me the error log by going to Help menu -> Report Bugs -> Email error logs -> Attach the log file to the email.

**Comment by ganeshrvel** [comment] 2020-12-11 14:30
Hey @miharekar, I got the error log. Looks like MTP kernel isn't able to detect the Garmin device. I would like to add the support for the Garmin device but unfortunately I don't have a device with me. 

If you are willing to contribute to the MTP kernel then please checkout https://github.com/ganeshrvel/go-mtpx/ and https://github.com/ganeshrvel/go-mtpfs/ . I am willing to extend my support to get the devices working on OpenMTP.

**Comment by miharekar** [comment] 2020-12-11 14:35
Yeah, I get it. It's impossible to debug without a device. I have an app running on garmin watches and on some of them it just doesn't work and I have no way of figuring it out.

However I also don't know `go` and don't own any Android devices at all, and all of this goes way above my abilities 😅 

Maybe @wadewegner can help out?

I stumbled upon this completely randomly by a tweet and then just wanted to check if it works with Garmin. I use AFT once every 3 months or so, so it's not a huge pain for me.

**Comment by ganeshrvel** [comment] 2020-12-11 14:37
Damn them Google guys. Their app has support for every device but the app is crap.

**Comment by slamble** [comment] 2020-12-24 10:11
I'm trying to figure this out. Is it a simple matter of adding the vendor and device ID (as seems to be the case for libmtp - see https://github.com/libmtp/libmtp/blob/master/src/music-players.h to understand what I'm getting at)? Or is it a little more complicated than that?

I have the Fenix 6s (vendor ID 0x091e, device ID 0x4cd8), so testing it isn't difficult - it's simply that I'm not familiar with go, and figuring out the code flow is proving to be frustrating for me. (Spot the C/Python guy. :) )

**Comment by fulmar2** [comment] 2021-02-02 15:39
Same situation here, interested in using OpenMTP to connect to a Garmin Fenix 6x.  Let me know if I can help.

**Comment by ganeshrvel** [comment] 2021-02-02 15:42
@fulmar2 Unfortunately I dont have a Garmin device but if you are willing to contribute to the MTP kernel, please feel free to contribute to [https://github.com/ganeshrvel/go-mtpfs](https://github.com/ganeshrvel/go-mtpfs). 

It's written in Go. Feel free to raise a pr, I will be happy to merge it.

Cheers!

**Comment by fallingrock** [comment] 2021-07-28 15:45
I'd love to see Garmin device support as well.
I'm not a go programmer (Java & RPG are my thing), but I'm happy to provide diagnostics & information as needed.

**Comment by mbirth** [comment] 2021-09-23 20:26
For a list of MTP devices, see https://github.com/libmtp/libmtp/blob/master/src/music-players.h .

**Comment by T-Bone90** [comment] 2022-04-30 20:31
I have search for an alternative to Android File Transfer and found OpenMTP. But Unfortunately I need this for an Garmin Fenix 6.
Any News about adding support for Garmin Devices? :-)
Thanks in advance.

**Comment by ganeshrvel** [comment] 2022-05-27 05:35
Unfortunately I dont have a `Garmin` with me to test this. 
Would any of you be interested in taking a look at the OpenMTP kernel code, which is written in Go, so that we could add the support for `Garmin` devices.

**Comment by slamble** [comment] 2022-06-07 01:21
As I said in December 2020, I'm more than happy to have a look at this - but I have absolutely no idea where to start. How does the code decide to try to open a particular device? What functions, in which files, are likely to be key? I've looked through the code, but it's not clear to me (at least partially because I am not a Go programmer; I've worked with C, C++, Bourne shell, Korn shell, Python, and a few others over the years.)

If you can give me some sort of an idea of where to start, I'm more than willing to dig - Garmin's Android File Transfer irritates me - but right now, I'm simply going round in circles.

**Comment by mcheban** [comment] 2022-06-08 10:57
what I found from [go-mtpfs sources](https://github.com/ganeshrvel/go-mtpfs) there's python script [munge.py](https://github.com/ganeshrvel/go-mtpfs/blob/master/mtp/munge.py) which parses [ptp.h](https://github.com/libmtp/libmtp/blob/master/src/ptp.h) and produces [const.go](https://github.com/ganeshrvel/go-mtpfs/blob/master/mtp/const.go) file with constants, and I didn't find any Garmin mentions in `ptp.h` file, I wonder if @ganeshrvel could use data from [music-players.h](https://github.com/libmtp/libmtp/blob/master/src/music-players.h) in additon to `ptp.h`

**Comment by slamble** [comment] 2022-06-22 06:57
I tried to get a development environment up and running to try to figure this one out, but it ended up being too hard. The electron version that's set as a requirement is too old (there's no ARM64 version of it for macOS; I have a Mac Studio), and when I tried to figure out how to move past that, I ran into a slew of issues with trying to get things to build.

I'd love to help out, but I simply don't have the time to learn these environments well enough to fix all of those issues and move on to the actual problem at hand. Maybe once M1 support is out of alpha. :/

**Comment by CodyJung** [comment] 2022-07-17 02:06
Some progress:

The first problem is that Garmin devices are reporting an empty string descriptor for Manufacturer and Product. All three string descriptors are technically optional, so I _think_ this chunk of code in [go-mtpfs/mtp.go](https://github.com/ganeshrvel/go-mtpfs/blob/master/mtp/mtp.go) isn't quite right:
```go
func (d *Device) ID() (string, error) {
	if d.h == nil {
		return "", fmt.Errorf("mtp: ID: device not open")
	}

	var ids []string
	for _, b := range []byte{
		d.devDescr.Manufacturer,
		d.devDescr.Product,
		d.devDescr.SerialNumber} {
		s, err := d.h.GetStringDescriptorASCII(b)
		if err != nil {
			if d.USBDebug {
				log.Printf("USB: GetStringDescriptorASCII, err: %v", err)
			}
			return "", err // This is the problem line - only SerialNumber is valid
		}
		ids = append(ids, s)
	}

	return strings.Join(ids, " "), nil
}
```

I've been able to get past that point by replacing that problem line with just `s = ""`, but now it looks like the first bulk read is timing out. I'll keep digging.

**Comment by CodyJung** [comment] 2022-07-23 21:06
Great news -
![image](https://user-images.githubusercontent.com/484512/180622384-0d5d293c-c0fc-4561-8f5e-136ef64dc6d5.png)

The issue with the bulk transfer was because Garmin devices follow this method of transfer (from the MTP spec v1.1):
![image](https://user-images.githubusercontent.com/484512/180622474-6c4ce9d5-73df-4735-b3a4-b38b4220c153.png)

`mtp.go` anticipates that case correctly; during the data phase if it receives a packet of type `USB_CONTAINER_DATA` it will attempt to read the data packet. However, this chunk of code isn't quite right:
```go
		if len(rest)+usbHdrLen == fetchPacketSize {
			// If this was a full packet, read until we
			// have a short read.
			_, finalPacket, err = d.bulkRead(dest)
			if err != nil {
				return err
			}
		}
```

Although we don't have a "full" 512-byte packet, the 12-byte packet that the Garmin device was sending in response to the GetStorageIDs command said to anticipate a 20-byte response (`h.Length`). It then followed that 12-byte packet up with an 8-byte packet for the payload/remainder of the response, but that packet doesn't have the full USB header again so was failing a later check.

I updated `fetchPacket()` to also return the number of bytes actually read from BulkTransfer, and then added to that check above:
```go
                // n here is returned from d.h.BulkTransfer() in fetchPacket()
		if len(rest)+usbHdrLen == fetchPacketSize || uint32(n) < h.Length {
                    ...
```

I'm mostly a C developer, so I don't know much about Go coding standards. I can put up a pull request if you'd like but it _might_ be faster for someone who knows Go better than me.

**Comment by CodyJung** [comment] 2022-07-24 01:09
I've put up a pull request in ganeshrvel/go-mtpfs -- if anyone else wants to pull down that repo and build+test I'd appreciate it. This is my first time writing Go code so it's probably rough. :)

**Comment by ganeshrvel** [comment] 2022-07-24 01:13
Thanks @CodyJung I have been following the developments. Let me take a look at it. If the test passes I will release it along with apple silicone support.

**Comment by lrk** [comment] 2022-09-16 14:04
Hello everyone.

Any news or ETA for a garmin devices support ?

**Comment by ganeshrvel** [comment] 2022-11-01 20:14
OpenMTP-3.2.0-beta.1 is out 🔥🔥

Note: This a pre-release version and the app might be unstable. ⚠️

### Features
- Much awaited Apple Silicone support 🔥🔥
- Garmin device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/1) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Fujifilm device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/2) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Other UI optimization and performance improvements


**Special shoutout to [@CodyJung](https://github.com/CodyJung "CodyJung") for adding the [Fujifilm](https://github.com/ganeshrvel/go-mtpfs/pull/2) and [Garmin](https://github.com/ganeshrvel/go-mtpfs/pull/1) devices support.** 🔥🔥


#### Downloads

macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)
macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)

**Comment by ganeshrvel** [comment] 2022-11-01 20:24
cc: @wadewegner @miharekar @slamble @fulmar2 @fallingrock @mbirth @T-Bone90 @mcheban @lrk 

Please download the DMG from the appropriate URL and do let me know if the app reads your device.

**Comment by slamble** [comment] 2022-11-01 21:49
I've just tried to use the 3.2.0-beta1 ARM64 release on my Mac Studio to connect to my Garmin Fenix 7s. Unfortunately, it didn't work. I then tried the Intel release (using Rosetta), without success.

The next step was to purge all copies of Android File Transfer and kill its helper app. No change.

I have an old Fenix 6s lying around - it needs to charge up a bit before it'll do anything, but I'll report back if I have any success with it.

**Comment by slamble** [comment] 2022-11-01 21:52
No success with the 6s. One thing that I did observe: when changing from Kalam to Legacy mode, I receive the error message, "Oops.. Your Phone has gone crazy! Try again."

I'll submit the error logs now.

**Comment by mcheban** [comment] 2022-11-01 21:55
same with my Fenix 6S 😞
I used [openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg) for my Apple Silicone Macbook (macOS Monterey 12.6.1)

**Comment by slamble** [comment] 2022-11-01 21:58
Also - the link to the download for the Intel version points to the ARM version. Going to https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.0-beta.1 lets the user download the right version, though (https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-x64.dmg is the correct link for Intel Macs.)

**Comment by CodyJung** [comment] 2022-11-01 22:13
Thanks all!

@ganeshrvel I’ll take a look tonight and see what I can figure out.

**Comment by CodyJung** [comment] 2022-11-04 03:42
Ok, so I _think_ I've identified the issue and have a PR up in go-mtpfs to fix it. The gritty details are available on the PR linked above.

I've been able to use mtpfs directly to mount the filesystem and read/write to it (I did need to update go-fuse to 2.1.0 and sys to 0.1.0 though):
<img width="682" alt="Screen Shot 2022-11-03 at 10 16 31 PM" src="https://user-images.githubusercontent.com/484512/199879681-eee02dd2-9ed8-48ce-ac77-5a9ddf326ae6.png">

I've also been able to get the unit tests in go-mtpx running (though it doesn't quite make it through the full suite so there might be something there to look into still).

Unfortunately, I haven't been able to get OpenMTP itself working. I don't know if I've just set something up wrong in my build and it's not bringing in my changes or what (I'm running `zx ./ffi/kalam/native/scripts/build.mjs` then `yarn` then `yarn dev`). Here's hoping an official build fixes that?

**Comment by ganeshrvel** [comment] 2022-11-04 03:44
Thank you for this. Let me take a look at it.

Thanks @CodyJung

**Comment by ganeshrvel** [comment] 2022-11-04 09:36
> Unfortunately, I haven't been able to get OpenMTP itself working. I don't know if I've just set something up wrong in my build and it's not bringing in my changes or what (I'm running `zx ./ffi/kalam/native/scripts/build.mjs` then `yarn` then `yarn dev`). Here's hoping an official build fixes that?


- You need to checkout the `release/m1` branch to get this script working, it takes care of both intel and m1 builds (https://github.com/ganeshrvel/openmtp/tree/feature/m1). The [release/m1](https://github.com/ganeshrvel/openmtp/tree/feature/m1) branch has many improvements in the build setup while the master requires some workaround to get the mtpx compile.
- Follow [go-mtpx instructions](https://github.com/ganeshrvel/go-mtpx/blob/master/README.md)
- Follow [OpenMTP build script instructions](https://github.com/ganeshrvel/openmtp/blob/feature/m1/ffi/kalam/native/README.md)
- make sure that you are still on [release/m1](https://github.com/ganeshrvel/openmtp/tree/feature/m1)
- yarn
- yarn dev

**Comment by ganeshrvel** [comment] 2022-11-04 09:41
OpenMTP-3.2.0-beta.2 is out 🔥🔥

Note: This a pre-release version and the app might be unstable. ⚠️


### Changelog
- Garmin device support patches - https://github.com/ganeshrvel/go-mtpfs/commit/0d40588840c526d36406e568c2e81394a4fc8b65

Thanks @CodyJung for the the patch https://github.com/ganeshrvel/go-mtpfs/pull/4 🔥🔥


### Download

macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.2/openmtp-3.2.0-beta.2-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.2/openmtp-3.2.0-beta.2-mac-arm64.dmg)
macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.2openmtp-3.2.0-beta.2-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.2/openmtp-3.2.0-beta.2-mac-x64.dmg)

**Comment by T-Bone90** [comment] 2022-11-04 11:43
Thanks for your great work!
But I can't connect to my Fenix 6 Sapphire. The right window is empty.

**Comment by CodyJung** [comment] 2022-11-04 12:33
@T-Bone90  Thanks for checking!
@ganeshrvel I think that’s what I’ve been doing. 😕 I’ll keep digging, though it would help a lot if I had access to the MTP Debug messages from the kernel. Is there a good way to get those printed somewhere? It seems like even if they are forced on in mtpx they don’t print when used as a dylib in openmtp.

**Comment by ganeshrvel** [comment] 2022-11-04 12:52
@CodyJung could you post screenshots or a video recording of the error/logs that you are getting while trying to start OpenMTP in dev mode?


or you could email me on ganeshrvel@outlook.com . Let's schedule a Google meet/zoom call and I shall help you with the OpenMTP dev setup.

**Comment by ganeshrvel** [comment] 2022-11-04 12:56
@T-Bone90 

Could try these?

1) Reboot your Mac (IMPORTANT). Simply restarting the machine has helped many.

2) Do you have Google drive installed on your MacBook? If yes, try to quit it "completely" and then try launching openmtp again. See if Dropbox or OneDrive is installed, quit them completely. Some applications will lock on to the usb port once it detects a usb drive. See if any of the active apps require usb access which might be causing this issue.

3) Uninstall any Samsung switch residue, if you have any: https://github.com/ganeshrvel/openmtp/issues/270

4) Try disabling the hotplug detection from settings in OpenMTP. and then tap on the refresh button

**Comment by CodyJung** [comment] 2022-11-04 13:07
> @CodyJung could you post screenshots or a video recording of the error/logs that you are getting while trying to start OpenMTP in dev mode?
> 
> or you could email me on [ganeshrvel@outlook.com](mailto:ganeshrvel@outlook.com) . Let's schedule a Google meet/zoom call and I shall help you with the OpenMTP dev setup.

I'm able to get it running; just no luck with actually printing out MTP traffic:
<img width="1038" alt="Screen Shot 2022-11-04 at 8 05 55 AM" src="https://user-images.githubusercontent.com/484512/199979598-885678d6-2c54-4522-9ff4-f77bba67844e.png">

**Comment by ganeshrvel** [comment] 2022-11-04 13:21
Try running any of these executable inside OpenMTP's build directory, this prints out some basic device information. 

```
# apple silicone
./build/mac/bin/arm64/kalam_debug_report


# Intel silicone
./build/mac/bin/amd64/kalam_debug_report
```

- Edit `openmtp/ffi/kalam/native/kalam_debug_report/main.go` and you could print the information that you need. You could call the Upload/Download/Walk/Delete or any other methods that are available in go-mtpx. Refer to `*_test.go` files in https://github.com/ganeshrvel/go-mtpx for the implementation.
- Save the file
- `zx ./ffi/kalam/native/scripts/build.mjs`
- `./build/mac/bin/arm64/kalam_debug_report`


Hope this helps

**Comment by CodyJung** [comment] 2022-11-05 00:51
@ganeshrvel Perfect! Thank you!

Got 'em:
<img width="1437" alt="Screen Shot 2022-11-04 at 7 49 02 PM" src="https://user-images.githubusercontent.com/484512/200093617-e37d432e-4060-4b88-bbd5-0550998c39f0.png">

PR incoming.

**Comment by ganeshrvel** [comment] 2022-11-05 04:23
Awesome work @CodyJung 🎉🎉

**Comment by ganeshrvel** [comment] 2022-11-05 06:28
# About OpenMTP-3.2.0-beta.3 🔥🔥

Note: This a pre-release version and it might be unstable. ⚠️

### Changelog
- Garmin device should work fine now - https://github.com/ganeshrvel/go-mtpfs/pull/5


Thanks @CodyJung for the the patch https://github.com/ganeshrvel/go-mtpfs/pull/5 🔥🔥


### Download

- macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-arm64.dmg)
- macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3openmtp-3.2.0-beta.3-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-x64.dmg)

**Comment by ganeshrvel** [comment] 2022-11-05 06:29
cc: @slamble  @T-Bone90

Please download the DMG from the above comment and do let me know if the app reads your device.

**Comment by T-Bone90** [comment] 2022-11-05 09:46
Thanks a lot for this incredible work!
My Fenix 6 sapphire works now in Kalam Mode with the new Beta 3.

PS.: It is possible to make the Openmtp Icon on Mac more angular to match the shape of the new macos icons? :-)

**Comment by slamble** [comment] 2022-11-06 04:45
Beta 3 is confirmed functional (at least to the point of seeing the device and the directory structure) on my M1-class Mac with both a Fenix 6s and a Fenix 7s. Thank you so much - it's fantastic to finally be able to get rid of that piece of junk known as Android File Transfer. I'll update if I find any issues with transferring files on or off the device, but I do not expect that to be the case.

Note for others wanting to test: before OpenMTP will pick up on the device, you must quit the open Android File Transfer application to release it. Quitting the helper app for AFT is not necessary.

**Comment by ganeshrvel** [comment] 2022-11-06 05:23
It's best to uninstall android file transfer. At times an active aft helper causes kernel panic. The aft helper doesn't get killed that easily, always. 





Latest Google drive and dropbox are notoriously known to interfere with OpenMTP's functioning. Completely quit both apps. 

Also uninstall Samsung SmartSwitch if you have installed them on macos.

https://github.com/ganeshrvel/openmtp/issues/270#issuecomment-1297386805

**Comment by ganeshrvel** [comment] 2022-11-06 05:25
If anyone owns a Zune, do check if it works.

Thanks!

**Comment by ganeshrvel** [comment] 2022-11-13 22:15
OpenMTP v3.2.0 supports Garmin devices: https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.0

Closing this issue.

Thank you all!

**Closed by ganeshrvel** 2022-11-13 22:15 UTC
Labels: enhancement

**Comment by hoyhoy** [comment] 2024-08-06 17:32
The Garmin Edge 1050 doesn't appear to work with OpenMTP on macOS 14.6.
