### ISSUE TITLE
Blank screen when transferring large files

### ISSUE THREAD

**Issue by DGatere** [ganeshrvel/openmtp#290] opened 2022-11-14 06:04 UTC
I've been having a strange problem where large file transfers (20GB with each file about 2GB) begin normally but after some time a blank OpenMTP screen appears and its not clear if the transfer is proceeding due to zero visual feedback indicating as much. Attached a log of the issue and a screenshot of how it appears on my device. The progress bar on the app in the dock freezes as well. This is on openmtp 3.2.0, also experienced this on beta 3. I'm Ventura 13.0.1. Smaller file transfers usually finish without triggering this problem.

[OpenMTP-log.zip](https://github.com/ganeshrvel/openmtp/files/10000025/OpenMTP-log.zip)
<img width="1800" alt="Screenshot 2022-11-14 at 08 17 54" src="https://user-images.githubusercontent.com/4351421/201586556-aabff356-e088-4f9e-ab5e-8d917ce23d4f.png">

**Comment by ganeshrvel** [comment] 2022-11-15 04:59
Do check this out? https://github.com/ganeshrvel/openmtp/issues/276

**Comment by broxio** [comment] 2022-11-18 01:53
It's happen to me on pixel 6  with about 20K picture in DCIM folder.

**Comment by alberto56** [comment] 2022-12-01 19:49
> btw switch from MTP:kalam mode back to legacy

@broxio Can you kindly explain what this means? I have followed all the tips from #276 and, after reboot, with no other apps running, with mac OS 13.0.1 and OpenMTP Version 3.2.0 (3.2.0.6) I am experiencing this issue with two different working USB cables.

**Comment by alberto56** [comment] 2022-12-05 20:59
Just some more observations about this:

I have certain files on my phone which around 3Gb. 

These are videos in a directory which contains 1846 files. 

When I try transferring the entire directory, the transfer fails and it shows a blank screen.

However it is still possible to transfer files individually. So I transfer my files in batches of 100 files, and then I individually transfer any file which is greater in size than 1Gb.

**Comment by ganeshrvel** [comment] 2022-12-18 19:38
I am trying to identify this issue. Looks like a node-napi error. I will post further updates soon. Follow the PR #303 for the updates

**Comment by ganeshrvel** [comment] 2022-12-18 19:38
I am trying to identify this issue. Looks like a node-napi error. I will post further updates soon. Follow the PR #303 for the updates

**Comment by ganeshrvel** [comment] 2022-12-20 16:56
Thanks @alecmuffett for the report. Looks like there has been a regression in ffi-napi package unfortunately I cannot revert back the package upgrade. I have reported the issue with them: https://github.com/node-ffi-napi/node-ffi-napi/issues/235.

Meanwhile I am looking into migrating the ffi package to something else which is stable.

**Comment by ganeshrvel** [comment] 2022-12-20 16:56
Looks like there has been a regression in ffi-napi package unfortunately I cannot revert back the package upgrade. I have reported the issue with them: https://github.com/node-ffi-napi/node-ffi-napi/issues/235.

Meanwhile I am looking into migrating the ffi package to something else which is stable.

**Comment by ganeshrvel** [comment] 2023-01-27 16:15
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing

**Closed by ganeshrvel** 2023-01-27 16:15 UTC
Labels: bug
