### ISSUE TITLE
Support FujiFilm Camera MTP

### ISSUE THREAD

**Issue by niklasarnitz** [ganeshrvel/openmtp#259] opened 2022-05-10 13:52 UTC
Fujifilm Cameras also use MTP as a transfer protocol.
Getting files of them without using a SD-Card reader is a huge pain in the a*s on macOS.

It would be awesome if openmtp would support them.

**Comment by ganeshrvel** [comment] 2022-05-27 05:34
unfortunately I dont have a `FujiFilm Camera` with me to test this. 
Are you by any chance interested in taking a look at the OpenMTP kernel code, which is written in Go, so that we could add the support for `FujiFilm` camera.

**Comment by CodyJung** [comment] 2022-07-26 02:38
@ganeshrvel  - I actually have a FujiFilm camera! The problem is it is returning a `InterfaceStringIndex` of 0. You can check against `fujifilm.co.jp` in mtp.go if you want to add an MTPExtension check like the existing check for `microsoft/WindowsPhone`. I can also put up a PR in the next day or two if you'd prefer.

**Comment by ganeshrvel** [comment] 2022-07-26 02:40
That's awesome. You are a star contributor @CodyJung ! 😃

**Comment by ganeshrvel** [comment] 2022-07-26 14:26
@CodyJung any updates?

**Comment by ganeshrvel** [comment] 2022-11-01 20:20
OpenMTP-3.2.0-beta.1 is out 🔥🔥

Note: This a pre-release version and the app might be unstable. ⚠️

### Features
- Much awaited Apple Silicone support 🔥🔥
- Garmin device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/1) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Fujifilm device support - [PR](https://github.com/ganeshrvel/go-mtpfs/pull/2) by [@CodyJung](https://github.com/CodyJung "CodyJung")
- Other UI optimization and performance improvements


**Special shoutout to [@CodyJung](https://github.com/CodyJung "CodyJung") for adding the [Fujifilm](https://github.com/ganeshrvel/go-mtpfs/pull/2) and [Garmin](https://github.com/ganeshrvel/go-mtpfs/pull/1) devices support.** 🔥🔥


### Download

macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)
macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.1/openmtp-3.2.0-beta.1-mac-arm64.dmg)

**Comment by ganeshrvel** [comment] 2022-11-05 11:09
Please download the latest beta version of openmtp and do let me know if Fujifilm camera works.

- macOS Apple Silicone (arm64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-arm64.dmg)
- macOS Intel (x64): [https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3openmtp-3.2.0-beta.3-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.0-beta.3/openmtp-3.2.0-beta.3-mac-x64.dmg)

Thanks

Cc @niklasarnitz @CodyJung

**Comment by CodyJung** [comment] 2022-11-05 21:15
Seems to work with my X-E3:
<img width="933" alt="Screen Shot 2022-11-05 at 4 14 22 PM" src="https://user-images.githubusercontent.com/484512/200141610-8d68c612-f573-487a-ac1e-f6025637c8ee.png">

**Comment by CodyJung** [comment] 2022-11-05 21:19
I will say that it can take a while to enumerate all the files in the folder, so some sort of progress indicator (or even a busy spinner) could be helpful. That's a separate ticket though. 😃

**Comment by ganeshrvel** [comment] 2022-11-13 22:14
@CodyJung yes. I could add a separate ticket for the same.

**Comment by ganeshrvel** [comment] 2022-11-13 22:15
OpenMTP v3.2.0 supports Fujifilm devices: https://github.com/ganeshrvel/openmtp/releases/tag/v3.2.0

Closing this issue.

Thank you!

**Closed by ganeshrvel** 2022-11-13 22:15 UTC
Labels: enhancement
