### ISSUE TITLE
OpenMTP 3.2.0.6 on Monterey 12.6.1 talking to Pixel4XL, Kalam Mode: app pulls about 150 files and crashes, pane goes grey. POSSIBLE WORKAROUND

### ISSUE THREAD

**Issue by alecmuffett** [ganeshrvel/openmtp#302] opened 2022-12-10 00:33 UTC
**Spoiler**

This seems only to affect Kalam-mode transfers; I re-ran the transfer under "Legacy" mode, and it worked.

**Describe the bug**

I fired up the app for the first time in several months; it autoupdated and restarted.  Since the update, asking it to pull a DCIM folder from my phone to my desktop, it manages to pull about 150 files (variable per attempt) and then somehow crashes, leading to the OpenMTP pane blacking out although the menubar is still somewhat functional.

I repeated this 3x, same results each time.  

I decided to try running it in a iTerm window, and the log is:

```
$ ./OpenMTP
objc[33898]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4a47fec8) and /Applications/OpenMTP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1137829c8). One of the two will be used. Which one is undefined.
2022/12/09 23:59:32 fatal error LIBUSB_ERROR_NOT_FOUND; closing connection.
Checking for update
Update for version 3.2.0 is not available (latest version: 3.2.0, downgrade is disallowed).
2022/12/09 23:59:47 OpenSession failed: LIBUSB_ERROR_TIMEOUT; attempting reset
2022/12/09 23:59:47 fatal error LIBUSB_ERROR_NOT_FOUND; closing connection.
2022/12/10 00:00:04 fatal error LIBUSB_ERROR_NOT_FOUND; closing connection.
libc++abi: terminating with uncaught exception of type Napi::Error: readPointer: Cannot read from nullptr pointer
```

The fatal "libusb" errors don't appear to actually be fatal since it pulls about 150 files, but the null pointer error comes up when it crashes properly.

**Steps to Reproduce (for bugs)**
Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant

1. Pull a large folder containing ~1100+ JPGs from an up-to-date Pixel phone, to a Monterey Mac, in Kalam mode.

**Context**
How has this issue affected you? What are you trying to accomplish?

File transfers of photos.  Came to a complete stop.

**Comment by Saber-CC** [comment] 2022-12-13 08:27
I have a similar situation to you.I have about 20,000 pictures to transfer, but every time I transfer thousands of pictures, the program will crash and turn gray.I tried [issues#276](https://github.com/ganeshrvel/openmtp/issues/276) and nothing worked
I used your method to changed the mode to Legacy,and finally the transmission was successful.
This may a bug.

**Comment by ganeshrvel** [comment] 2022-12-13 12:55
This seems like an issue with the node napi package that i am using. Unfortunately i am not getting enough time to find a fix for this issue.

**Comment by ganeshrvel** [comment] 2022-12-20 16:54
Thanks @alecmuffett for the report. Looks like there has been a regression in ffi-napi package. I have reported the issue with them: https://github.com/node-ffi-napi/node-ffi-napi/issues/235.

Meanwhile I am looking into migrating the ffi package to something else which is stable.

**Comment by ganeshrvel** [comment] 2023-01-25 18:28
OpenMTP v3.2.10-beta.1 is now rolling out.

Note: This a pre-release version and it might be unstable. ⚠️

### Features
- Fixes - the app crash on older versions of macOS
- Fixes - the app crash caused while transferring files a large number of files.

------------


If you are on an older version of OpenMTP and have frozen the auto-app update option for the sake of preventing the app crash, you may re-enable it from `Settings > Updates > Automatically Check for Updates`


Note: We have now officially retired the support for Kalam Kernel on macOS 10.13 (OS X El High Sierra) and lower. Though the "Legacy" MTP mode will continue working on these outdated machines.
Read more: https://github.com/ganeshrvel/openmtp/tree/release/3.2.10-beta.1#system-requirements-and-support


Download: 
- Apple Silicon (mac M1/M2): [openmtp-3.2.10-beta.1-mac-arm64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-arm64.dmg)
- Intel Silicon (Older mac): [openmtp-3.2.10-beta.1-mac-x64.dmg](https://github.com/ganeshrvel/openmtp/releases/download/v3.2.10-beta.1/openmtp-3.2.10-beta.1-mac-x64.dmg)

**Comment by ganeshrvel** [comment] 2023-01-27 16:15
Fixed the issue in https://github.com/ganeshrvel/openmtp/pull/314. Closing

**Closed by ganeshrvel** 2023-01-27 16:15 UTC
Labels: bug
